version: "2"
linters:
  default: all
  disable:
    - wsl # deprecated (since v2.2.0)
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/aws/aws-sdk-go-v2/aws
            - github.com/aws/aws-sdk-go-v2/config
            - github.com/aws/aws-sdk-go-v2/service/sts
            - github.com/aws/aws-sdk-go-v2/service/sts/types
            - github.com/pkg/browser
            - github.com/wakeful/aws-console/pkg/console
    revive:
      rules:
        - name: package-comments
          disabled: true
  exclusions:
    generated: disable
    rules:
      - path: _test.go
        linters:
          - exhaustruct
          - funlen
          - lll
          - testpackage
          - varnamelen
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
