linters:
  enable-all: true
  disable:
    - gomnd
    - execinquery
    - exhaustruct
    - exportloopref
    - tagliatelle
issues:
  exclude-rules:
    - path: _test.go
      linters:
        - exhaustruct
        - lll
        - paralleltest
        - testpackage
        - varnamelen
linters-settings:
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/aws/aws-sdk-go-v2/aws
          - github.com/aws/aws-sdk-go-v2/config
          - github.com/aws/aws-sdk-go-v2/service/sts
          - github.com/aws/aws-sdk-go-v2/service/sts/types
          - github.com/pkg/browser
          - github.com/wakeful/aws-console/pkg/console
